// <auto-generated />
namespace Yaxel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ComponentManufacturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComponentManufacturer));
        
        string IMigrationMetadata.Id
        {
            get { return "202205140920579_Component-Manufacturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
